apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
  namespace: {{ .Values.todoapp.namespace }}
spec:
  storageClassName: {{ .Values.todoapp.pv.storageClassName }}
  persistentVolumeReclaimPolicy: {{ .Values.todoapp.pv.persistentVolumeReclaimPolicy }}
  accessModes:
    - {{ .Values.todoapp.pv.accessModes }}
  capacity:
    storage: {{ .Values.todoapp.pv.storage }}
  hostPath:
    path: /data/
