
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Values.todoapp.namespace }}
spec:
  volumeName: {{ .Chart.Name }}-pv
  accessModes:
    - {{ .Values.todoapp.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.todoapp.pvc.storage }}